### ISSUE TITLE
Excuse me?

### ISSUE THREAD

**Issue by iann0036** [richardhboyd/hatchet#1]
https://github.com/richardhboyd/hatchet/blob/5837ea0ca83585a6656f5fa336362aba933154f1/template.yaml#L32-L36

**Comment by richardhboyd** [comment]
I said what I said!

**Comment by richardhboyd** [comment]
for serious though, I'll scope it down today.

**Comment by richardhboyd** [comment]
Fixed.
https://github.com/richardhboyd/hatchet/commit/1ed3cad02ff9a2d5d84d66d0eeb095631d5757f2

**Comment by richardhboyd** [comment]
Fixed.
https://github.com/richardhboyd/hatchet/commit/5305bb4439595e74a2b71b42ff2d28daa596862a
